# Generated by Django 2.0.5 on 2018-05-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipofuncionalidad',
            options={'verbose_name': 'Tipo de funcionalidad', 'verbose_name_plural': 'Tipos de funcionalidades'},
        ),
    ]
