# Generated by Django 2.0.5 on 2018-05-22 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180519_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipofuncionalidad',
            name='nombre_corto',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipofuncionalidad',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
