# Generated by Django 2.0.5 on 2018-05-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180516_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacion',
            options={'verbose_name': 'Aplicacion', 'verbose_name_plural': 'Aplicaciones'},
        ),
        migrations.AlterModelOptions(
            name='funcionalidad',
            options={'verbose_name': 'Funcionalidad', 'verbose_name_plural': 'Funcionalidades'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name': 'Modulo', 'verbose_name_plural': 'Modulos'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='sistema',
            options={'verbose_name': 'Sistemas', 'verbose_name_plural': 'Sistemas'},
        ),
    ]
