# Generated by Django 2.0.5 on 2018-05-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180522_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
