# Generated by Django 2.0.5 on 2018-05-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180516_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='sistema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Sistema'),
        ),
        migrations.AddField(
            model_name='funcionalidad',
            name='modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Modulo'),
        ),
        migrations.AddField(
            model_name='funcionalidad',
            name='tipo_funcionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.TipoFuncionalidad'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='aplicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Aplicacion'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Proyecto'),
        ),
    ]
