# Generated by Django 2.0.5 on 2018-05-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_modulo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
