# Generated by Django 2.0.5 on 2018-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_aplicacion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
