# Generated by Django 2.0.5 on 2018-05-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180516_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionalidad',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='funcionalidad',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
