# Generated by Django 2.0.5 on 2018-05-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_entidad_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='nombre',
            new_name='codigo',
        ),
    ]
