# Generated by Django 2.0.4 on 2018-04-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocomprobante',
            name='codigo',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
