# Generated by Django 2.0.4 on 2018-04-29 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compsender', '0003_auto_20180429_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='cae_vto',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprobante',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
