# Generated by Django 2.0.4 on 2018-04-29 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsender', '0005_auto_20180429_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='importe_no_gravado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='punto_venta',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_punto_venta', message='El pinto de venta debe ser un número de 1 a 9999', regex='[0-9]{4}')]),
        ),
    ]
