# Generated by Django 2.0.4 on 2018-04-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsender', '0009_auto_20180429_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='numero_comprobante',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='punto_venta',
            field=models.IntegerField(blank=True),
        ),
    ]
